code/LotterySystem/LotterySystem/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LotterySystem.Models;
using LotterySystem.Service.SysInfo;
using LotterySystem.Service;
namespace LotterySystem.Controllers
{
    public class HomeController : Controller
    {
        PlatService platService = ServiceContext.getInstance().getPlatService();
        private static log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
     
        public ActionResult Index(String msg)
        {
            SystemInfoModel sysInfo = ServiceContext.getInstance().getSysInfoService().loadSysInfo();
            if (null == sysInfo)
            {
                log.Error("can not get the system information");
            }
            else
            {
                ViewBag.RegistType = sysInfo.RegistType;
            }
            ViewBag.Msg = msg;
            return View();
        }


    }
}

code/LotterySystem/LotterySystem/Controllers/LogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LotterySystem.Service;
using LotterySystem.Po;
namespace LotterySystem.Controllers
{
    public class LogController : BaseController
    {

        LogService manageService = ServiceContext.getInstance().getLogService();

        
        public ActionResult LoginLog()
        {
            List<LoginLog> logList = manageService.getLoginLogList();
            ViewBag.LoginLogList = logList;
            ViewBag.LoginLogListCount = logList.Count;
            return View();     
        }

        public ActionResult ScoreLog()
        {
            List<ScoreLog> logList = manageService.getScoreLogList();
            ViewBag.ScoreLogList = logList;
  
            return View();
        }
    }
}

code/LotterySystem/LotterySystem/Controllers/SystemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LotterySystem.Service;
using LotterySystem.Models;

namespace LotterySystem.Controllers
{
    public class SystemController : BaseController
    {
        public ActionResult SystemManage()
        {
            //ViewBag.Msg = msg;
            SystemInfoModel sysInfo = ServiceContext.getInstance().getSysInfoService().loadSysInfo();

            ViewBag.SysInfo = sysInfo;
            return View();
        }

        public ActionResult modifySysInfo(SystemInfoModel sysInfo)
        {
            //ViewBag.Msg = msg;
            ServiceContext.getInstance().getSysInfoService().saveSysInfo(sysInfo);

            return RedirectToAction("Hall", "Game");
        }

 

    }
}

code/LotterySystem/LotterySystem/Views/Home/About.cshtml
@{
    ViewBag.Title = "关于";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        使用此区域可提供附加信息。
    </p>

    <p>
        使用此区域可提供附加信息。
    </p>

    <p>
        使用此区域可提供附加信息。
    </p>
</article>

<aside>
    <h3>副标题</h3>
    <p>
        使用此区域可提供附加信息。
    </p>
    <ul>
        <li>@Html.ActionLink("主页", "Index", "Home")</li>
        <li>@Html.ActionLink("关于", "About", "Home")</li>
        <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
    </ul>
</aside>

code/LotterySystem/LotterySystem/Views/Home/Index.cshtml
@model LotterySystem.Models.LoginModel
@{
    ViewBag.Title = "主页";
}
   

     <script src="@Url.Content("~/Content/js/bootstrap.min.js")">  </script>

    <div id="content"  style="text-align:center"> 
         @RenderPage("LoginHead.cshtml")
    </div>

   

code/LotterySystem/LotterySystem/Views/Home/IndexInfo.cshtml
@{
    ViewBag.Title = "HomeIndex";
}
	<!-- 轮播-->				
						<div id="myCarousel" class="carousel slide">
				
					<ol class="carousel-indicators">
					  <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
					  <li data-target="#myCarousel" data-slide-to="1"></li>
					  <li data-target="#myCarousel" data-slide-to="2"></li>
					</ol>
					
					<div class="carousel-inner">
						<div class="active item"><img  src="../Content/img/gallery-photo/1.png" height="10" alt="" ></div>
						<div class="item"><img  src="../Content/img/gallery-photo/2.png" height="10"alt="" ></div>
						<div class="item"><img src="../Content/img/gallery-photo/3.png" height="10"alt="" ></div>
					</div>
				   <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
				   <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
				</div>	<!-- 轮播-->

				<!-- 游戏资讯-->
					<div class="panel panel-primary">
					<div class="panel-heading">
						最新资讯
					</div>
					
					<div class="panel-body">

								<div class="new-update clearfix">
									<i class="icon-exclamation-sign"></i>
									<div class="update-alert">										
										<a title="" href="#"><strong>用户****今日设擂台，但求一败！！</strong></a>
										<span>请登录*****房间号*****桌号，或者直接搜索用户****，点击参与……</span>
									</div>
									<div><span class="pull-right">2014-08-23</span></div>
								</div>
								
								<div class="new-update clearfix">
									<i class="icon-ok-sign"></i>
									<div class="update-done">										
										<a title="" href="#"><strong>本系统用户量突破100万了！！！</strong></a>
										<span>****在线游戏平台经过长时间的实践检验，深受广大爱好者的喜欢，目前用户统计量已经达到101.781万人次！！</span>
									</div>
									<div><span class="pull-right">2014-08-20</span></div>
								</div>
								
								<div class="new-update clearfix">
									<i class="icon-question-sign"></i>
									<div class="update-notice">										
										<a title="" href="#"><strong>系统维护通知</strong></a>
										<span>由于系统更新，本平台将于2014年8月17日暂停服务一天（8:00-19:00），敬请谅解！</span>
									</div>
									<div><span class="pull-right">2014-08-16</span></div>
								</div>
					</div>
				</div><!-- 游戏资讯-->

code/LotterySystem/LotterySystem/Views/Home/LoginHead.cshtml
@{
    ViewBag.Title = "TitleLogIn";
}


<script type="text/javascript">
    function getBrowserInfo() {
        var agent = navigator.userAgent.toLowerCase();
        var regStr_ie = /msie [\d.]+;/gi;
        var regStr_ff = /firefox\/[\d.]+/gi
        var regStr_chrome = /chrome\/[\d.]+/gi;
        var regStr_saf = /safari\/[\d.]+/gi;
        //IE
        if (agent.indexOf("msie") > 0) {
            return agent.match(regStr_ie);
        }

        //firefox
        if (agent.indexOf("firefox") > 0) {
            return agent.match(regStr_ff);
        }

        //Chrome
        if (agent.indexOf("chrome") > 0) {
            return agent.match(regStr_chrome);
        }
    }

    function detectOS() {
        var sUserAgent = navigator.userAgent;
        var isWin = (navigator.platform == "Win32") || (navigator.platform == "Windows");
        var isMac = (navigator.platform == "Mac68K") || (navigator.platform == "MacPPC") || (navigator.platform == "Macintosh") || (navigator.platform == "MacIntel");
        if (isMac) return "Mac";
        var isUnix = (navigator.platform == "X11") && !isWin && !isMac;
        if (isUnix) return "Unix";
        var isLinux = (String(navigator.platform).indexOf("Linux") > -1);
        if (isLinux) return "Linux";
        if (isWin) {
            var isWin2K = sUserAgent.indexOf("Windows NT 5.0") > -1 || sUserAgent.indexOf("Windows 2000") > -1;
            if (isWin2K) return "Win2000";
            var isWinXP = sUserAgent.indexOf("Windows NT 5.1") > -1 || sUserAgent.indexOf("Windows XP") > -1;
            if (isWinXP) return "WinXP";
            var isWin2003 = sUserAgent.indexOf("Windows NT 5.2") > -1 || sUserAgent.indexOf("Windows 2003") > -1;
            if (isWin2003) return "Win2003";
            var isWinVista = sUserAgent.indexOf("Windows NT 6.0") > -1 || sUserAgent.indexOf("Windows Vista") > -1;
            if (isWinVista) return "WinVista";
            var isWin7 = sUserAgent.indexOf("Windows NT 6.1") > -1 || sUserAgent.indexOf("Windows 7") > -1;
            if (isWin7) return "Win7";
        }
        return "other";
    }

    window.onload = function () {
        $("#broswer").val(getBrowserInfo());
        $("#os").val(detectOS());
    }
</script>

<div class="row-fluid align-center">
    <div class="row">
        <div class="col-lg-4">
        </div>
        <div class="col-lg-4">

            <div class="panel panel-primary">
                <div class="panel-heading">
                    登录游戏
                </div>
                <div class="panel-body">
                    <div class="col-md-12">
                        <section id="loginForm">
                            @using (Html.BeginForm("Login", "Login", FormMethod.Post))
                            {
                                        
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true)	                              									
                                <div class="form-horizontal">
                                     <div class="form-group">

                                        <label class="control-label">
                                            @if (ViewBag.Msg == null)
                                            {

                                            }
                                            else
                                            {
                                                @ViewBag.Msg
                                            }
                                        </label>

                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">用户名</label>
                                        <div class="col-sm-9">
                                            <input name="UserName" type="text" class="form-control" >
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-sm-3 control-label">密&nbsp&nbsp&nbsp码</label>
                                        <div class="col-sm-9">
                                            <input name="Password" type="password" class="form-control" >
                                        </div>
                                    </div>
                                    <div class="form-group">
                                         @if ("停止注册".Equals(@ViewBag.RegistType))
                                         {
                                            <div class="col-xs-5"></div>  
                                            <div class="col-xs-2">
                                                 <input name="submit" type="submit" class="btn btn-primary" value="登录" />
                                             </div>
                                         }
                                         else
                                         {
                                             <div class="col-xs-2"></div>
                                             <div class="col-xs-4">
                                                 <input name="submit" type="submit" class="btn btn-primary" value="登录" />
                                             </div>
                                             <div class="col-xs-4">

                                                 @Html.ActionLink("注册", "Register", "Login", null, new { @class = "btn btn-primary" })
                                             </div>
                                             <input id="broswer" name="broswer" type="hidden" value="" />
                                             <input id="os" name="os" type="hidden" value="" />
                                             <div class="col-xs-2"></div>
                                         }
                                        
                                    </div>
                                </div>
                            }
                        </section>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-lg-4">
        </div>
    </div>

</div>
<!-- row-fluid -->

code/LotterySystem/LotterySystem/Views/Home/Nav.cshtml
@{
    ViewBag.Title = "导航栏";

    LotterySystem.Models.UserModel user = (LotterySystem.Models.UserModel)Session["SystemUser"];
     
}



<!--navbar--->
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a> @Html.ActionLink("游戏大厅", "Hall", "Game", null, new { @class = "navbar-brand" })</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
             <li>
                @Html.ActionLink("修改密码", "PasswordSet", "User", null, null)
            </li>

            @if (user.Permission.Contains("系统"))
            {
                <li>
                    @Html.ActionLink("系统管理", "SystemManage", "System", null, null)
                </li>
                
                
            }
              @if (user.Permission.Contains("游戏"))
            {
                <li>
                    @Html.ActionLink("游戏管理", "GameManage", "Game", null, null)
                </li>
            }
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">用户</a>
                    <ul class="dropdown-menu" role="menu">
                        <li>@Html.ActionLink("用户审核", "UserApprove", "User", null, null)</li>
                        @if (user.Permission.Contains("用户"))
                        {
                            <li>@Html.ActionLink("用户管理", "UserManage", "User", null, null)</li>
                        }
                    </ul>
                </li>
 
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">积分管理</a>   
                    <ul class="dropdown-menu" role="menu">
                        <li> @Html.ActionLink("积分记录", "ScoreRecord", "Score", null, null)</li>
                        <li> @Html.ActionLink("积分申借", "ScoreManage", "Score", null, null)</li>
				
                    </ul>

                </li>

            @if (user.Permission.Contains("日志"))
            {
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">日志</a>   
                    <ul class="dropdown-menu" role="menu">
                        <li>@Html.ActionLink("登录日志", "Loginlog", "Log", null, null)</li>
                        <li> @Html.ActionLink("积分日志", "ScoreLog", "Log", null, null)</li>
				
                    </ul>

                </li>

            }

            <li>
                @Html.ActionLink("退出", "LogOff", "Login", null, null)
            </li>
        </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            @if(@ViewBag.SuccessMsg!=null)
            {
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <strong>操作结果: </strong>@ViewBag.SuccessMsg
                </div>
            }

             @if(@ViewBag.ErrorMsg!=null)
            {
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <strong>操作结果: </strong>@ViewBag.ErrorMsg
                </div>
            }
             @if(@ViewBag.InfoMsg!=null)
            {
                <div class="alert alert-info alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <strong>操作结果: </strong>@ViewBag.InfoMsg
                </div>
            }

        </div>
    </div>
        
</div>

code/LotterySystem/LotterySystem/Views/Home/Ranking.cshtml
@{
    ViewBag.Title = "排行傍";
}
<!-- 风云榜-->
<div class="panel panel-primary">
    <div class="panel-heading">
        风云榜
    </div>
    <div class="panel-body">
        <h6>今日排行:</h6>
        <div class="list-group">
            <a href="#" class="list-group-item">冠军: XXX 20000</a>
            <a href="#" class="list-group-item">亚军: XXX 20000</a>
            <a href="#" class="list-group-item">季军: XXX 20000</a>
        </div>

        <h6>本周排行:</h6>
        <div class="list-group">
            <a href="#" class="list-group-item">冠军: XXX 20000</a>
            <a href="#" class="list-group-item">亚军: XXX 20000</a>
            <a href="#" class="list-group-item">季军: XXX 20000</a>
        </div>

        <h6>本月排行:</h6>
        <div class="list-group">
            <a href="#" class="list-group-item">冠军: XXX 20000</a>
            <a href="#" class="list-group-item">亚军: XXX 20000</a>
            <a href="#" class="list-group-item">季军: XXX 20000</a>
        </div>
    </div>
</div>
<!-- 风云榜-->

code/LotterySystem/LotterySystem/Views/Home/Test.cshtml
@{
    ViewBag.Title = "Test";
}
<div id="div1">
　　刷新此层
　</div>
　　
<div id="div2">
　　@Ajax.ActionLink("点此进行局部刷新","About","Home",new AjaxOptions{UpdateTargetId = "div1"})
　</div>